## Load packages

```{r}
library(tidyverse)
library(fgsea)
library(msigdbr)
library(patchwork)
```

## Rank data

```{r}
data_path <- '../PP1DTLeukemia_vs_WTLeukemia_none_filtered.csv'
data <- read_csv(data_path)

data

v2_ranked <- data |>
        na.omit() |> 
        filter(padj < 0.05 & abs(log2FoldChange) > 1) |>  
        mutate(gene = str_remove(row, "\\..*")) |>
        mutate(rank = -log10(padj)) |> 
        arrange(-rank) |> 
        dplyr::select(gene, rank)

v2_ranked
```

## Fetch geneset

```{r}
# Look at species
msigdbr_species() 

gene_set <- msigdbr(species = "Mus musculus",
                    category = 'H')

BP_list = split(x = gene_set$ensembl_gene, f = gene_set$gs_name)

BP_list[2]
```

```{r}
v2_gene_stat <- v2_ranked |> 
        dplyr::select(rank) |> 
        unlist()

names(v2_gene_stat) <- v2_ranked$gene
```

```{r}
v2_fgseaRes <- fgsea(pathways = BP_list, stats = v2_gene_stat)
```

```{r}
dexsq <- read_tsv('../results_dexsq.tsv')
```

```{r}
dexseq_ranked <- dexsq |>
        dplyr::select(groupID, padj, log2fold_PPM1DT_leukemia_.wild_type_leukemia) |> 
        na.omit() |> 
        filter(padj < 0.05 & abs(log2fold_PPM1DT_leukemia_.wild_type_leukemia) > 1) |>  
        mutate(gene = str_remove(groupID, "\\..*")) |>
        mutate(rank = -log10(padj)) |> 
        arrange(-rank) |> 
        dplyr::select(gene, rank)
dexseq_ranked
```

```{r}
dexseq_stat  <- dexseq_ranked |> 
        dplyr::select(rank) |> 
        unlist()
        
names(dexseq_stat) <- dexseq_ranked$gene
```

```{r}
dexseq_Res <- fgsea(pathways = BP_list, stats = dexseq_stat)
```

```{r}
v2_fgseaRes <- v2_fgseaRes |>
        mutate(LOGp = -log10(padj)) |>
        mutate(Size = case_when( (LOGp < 0.10) ~ "FDR < 0.10",
                                (LOGp >= 0.10) & (LOGp < 0.15) ~ "FDR < 0.15",
                                 LOGp >= 0.15 ~ "FDR > 0.15")) |>
        mutate(FC = case_when(NES > 0 ~ 1,
                              NES < 0 ~ -1)) |>
        arrange(abs(NES)) |> 
        head(20) 
        
p1 <- ggplot(v2_fgseaRes,
             aes(x = NES, y = pathway, size = Size, fill = FC)) +
        geom_point(alpha = 0.75,shape = 21, color = "black", stroke = 1) +
        scale_fill_gradient(low = "blue", high = "red") +
        theme_minimal() +
        labs(title = 'DEseq2',
             x = "NES",
             y = NULL,
        size = NULL) +
        theme(plot.title = element_text(hjust = 0.5, size =10),
              legend.position = "none", 
              panel.grid.major.x = element_blank(),
              panel.grid.minor.x = element_blank()) +
        geom_vline(xintercept = 0, 
                   color = 'black', 
                   linetype = 'dashed',
                   size = 1) + 
        guides(fill = "none")

ggsave("DESeq_FGSEA.png", p1,height = 8, width = 8, bg = "white")

```

```{r}
dexseq_Res <- dexseq_Res |>
        mutate(LOGp = -log10(padj)) |>
        mutate(Size = case_when((LOGp < 0.015) ~ "FDR < 0.10",
                                (LOGp >= 0.015) & (LOGp < 0.15) ~ "FDR < 0.15",
                                 LOGp >= 0.15 ~ "FDR > 0.15")) |>
        mutate(FC = case_when(NES > 0 ~ 1,
                              NES < 0 ~ -1)) |> 
        arrange(abs(NES)) |> 
        head(20) 

p2 <- ggplot(dexseq_Res,
             aes(x = NES, y = pathway, size = Size, fill = FC)) +
        geom_point(alpha = 0.75,shape = 21, color = "black", stroke = 1) +
        scale_fill_gradient(low = "blue", high = "red") +
        theme_minimal() +
        labs(title = 'DEXseq',
             x = "NES",
             y = NULL,
        size = 'FDR') +
        theme(plot.title = element_text(hjust = 0.5, size =10),
              legend.position = "right", 
              panel.grid.major.x = element_blank(),
              panel.grid.minor.x = element_blank()) +
        geom_vline(xintercept = 0, 
                   color = 'black', 
                   linetype = 'dashed',
                   size = 1) + 
        guides(fill = "none")
        

ggsave("DEXSeq_FGSEA.png", p2,height = 8, width = 8, bg = "white")
```

```{r}
p3 <- p1+p2
ggsave("combined.png", p3,height = 8, width = 15, bg = "white")
```
